### ISSUE TITLE
Template fails at task 5 (both on Linux and Windows)

### ISSUE THREAD

**Issue by Gregorgeous** [hypermedia-app/creta-template-app#32]
## Steps to reproduce 
1. In a separate repo set up all the deps according to the readme.
2. run `copier https://github.com/hypermedia-app/creta-template-app.git test`
3. Leave all copier questions to default answers

## Excerpt from the error stack trace: 
```
 > Running task 1 of 10: git init
Initialized empty Git repository in /home/greg/Data-Mazes/testing/test/.git/
 > Running task 2 of 10: npx npm-add-script -f -k copier:api -v "copier -a .copier-api.yaml update"; 
npx: installed 19 in 4.123s
ADDED copier:api TO YOUR PACKAGE dot JASON
 > Running task 3 of 10: npx npm-add-script -f -k "bootstrap:vocabs" -v "talos put-vocabs --endpoint \$SPARQL_ENDPOINT --user \$SPARQL_USER --password \$SPARQL_PASSWORD"
npx: installed 19 in 1.078s
ADDED bootstrap:vocabs TO YOUR PACKAGE dot JASON
 > Running task 4 of 10: npx npm-add-script -f -k start -v "knossos-ts serve \$SPARQL_ENDPOINT --name \$APP_NAME --user \$SPARQL_USER --password \$SPARQL_PASSWORD"
npx: installed 19 in 1.137s
ADDED start TO YOUR PACKAGE dot JASON
Traceback (most recent call last):
  File "/home/greg/Data-Mazes/testing/venv/bin/copier", line 8, in <module>
    sys.exit(CopierApp.run())
  File "/home/greg/Data-Mazes/testing/venv/lib/python3.8/site-packages/plumbum/cli/application.py", line 629, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/home/greg/Data-Mazes/testing/venv/lib/python3.8/site-packages/plumbum/cli/application.py", line 624, in run
    retcode = inst.main(*tailargs)
  File "/home/greg/Data-Mazes/testing/venv/lib/python3.8/site-packages/copier/cli.py", line 70, in _wrapper
    return method(*args, **kwargs)
  File "/home/greg/Data-Mazes/testing/venv/lib/python3.8/site-packages/copier/cli.py", line 293, in main
    self.parent._worker(
  File "/home/greg/Data-Mazes/testing/venv/lib/python3.8/site-packages/copier/main.py", line 586, in run_copy
    self._execute_tasks(
  File "/home/greg/Data-Mazes/testing/venv/lib/python3.8/site-packages/copier/main.py", line 174, in _execute_tasks
    task_cmd = self._render_string(task_cmd)
  File "/home/greg/Data-Mazes/testing/venv/lib/python3.8/site-packages/copier/main.py", line 523, in _render_string
    tpl = self.jinja_env.from_string(string)
  File "/home/greg/Data-Mazes/testing/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/greg/Data-Mazes/testing/venv/lib/python3.8/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/greg/Data-Mazes/testing/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: expected token 'in', got 'of'
```

**Comment by Gregorgeous** [comment]
Actually ... It seems the stack trace is a bit misleading - it's the task 5. that gives the error: 
```'npx npm-add-script -f -k "copier:root" -v "copier -a{% for api of apis %} -s apps/{{api}}{% endfor %} {{_copier_conf.answers_file}} update"'```
When I test it on both Linux and Windows removing that task makes the whole copier process work without errors. 
Removing any other task on either of the systems doesn't do any difference so it seems it's that one task that has some syntax/logic error and it's not anything OS-specific

**Comment by tpluscode** [comment]
Nice catch. Yea, the log mentions task 4, which apparently is the last which succeeds. Does not get to taks 5 because it fails to process jinja. The error is quite clear. Should it be like this instead?

```diff
-for api of apis
+for api in apis
```

**Comment by Gregorgeous** [comment]
Fixed in https://github.com/Gregorgeous/creta-template-app/commit/98453e19853c20dbd3fa9aadea374bf9deaa350e 👍
